FROM node:20-alpine

WORKDIR /app

# Copia los archivos necesarios
COPY package*.json ./
COPY prisma ./prisma
COPY . .

# Instala bcrypt con compilación compatible con Alpine
RUN apk add --no-cache python3 make g++ \
  && npm install \
  && apk del python3 make g++

# Genera Prisma si es necesario
RUN npx prisma generate

# Expón el puerto
EXPOSE 4000

CMD ["node", "backend/index.js"]
