// app/layout.tsx
import { Geist, Geist_Mono } from "next/font/google";
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import RouteTransitionSpinner from './components/RouteTransitionSpinner';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <RouteTransitionSpinner />
        {children}
      </body>
    </html>
  );
}